#!/usr/bin/env python3
"""
SQLAlchemy ORM models for SQL Server tables:
- APR_TITULOS
- APR_capa
- cedente
- CADASTRO_STATUS_FLUXO
"""

from datetime import datetime
from decimal import Decimal
from typing import Optional
from sqlalchemy import (
    Column, Integer, String, DateTime, Numeric, Boolean, Text,
    SmallInteger, CHAR, ForeignKey
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class APRTitulos(Base):
    """
    ORM model for APR_TITULOS table.
    Represents individual titles/invoices in the APR system.
    """
    __tablename__ = 'APR_TITULOS'
    
    # Primary Key (composite)
    DATA = Column(DateTime, primary_key=True, nullable=False)
    NUMERO = Column(Integer, primary_key=True, nullable=False)
    TIPO = Column(SmallInteger, primary_key=True, nullable=False, default=1)
    TITULO = Column(String(14), primary_key=True, nullable=False)
    BANCO = Column(String(3), primary_key=True, nullable=False, default='')
    AGENCIA = Column(String(5), primary_key=True, nullable=False, default='')
    CONTA = Column(String(10), primary_key=True, nullable=False, default='')
    CHEQUE = Column(String(6), primary_key=True, nullable=False, default='')
    
    # Regular columns
    PRACA = Column(String(2), default='')
    COMP = Column(SmallInteger, default=0)
    DV1 = Column(String(1), default='0')
    DV2 = Column(String(1), default='0')
    DV3 = Column(String(1), default='0')
    TIPIFICA = Column(String(1), default='0')
    VENCIMENTO = Column(DateTime, nullable=False)
    CNPJ = Column(String(14))
    APELIDO = Column(String(20))
    NOME = Column(String(50))
    VALOR = Column(Numeric(18, 2))
    MARCA_SCI = Column(String(1))
    STATUS = Column(Integer, default=0)
    SAC_EXISTE = Column(Boolean)
    DATA_SCI = Column(DateTime)
    CRITICA = Column(String(70), default='')
    GRAVADO = Column(Boolean, default=True)
    sequencial = Column(Integer, nullable=False)
    DESCONTO = Column(Numeric(18, 2))
    chave = Column(String(25), default='')
    SEUNO = Column(String(12))
    ENDERECO = Column(String(70))
    CEP = Column(String(8))
    CIDADE = Column(String(20))
    UF = Column(String(2))
    MENS1 = Column(String(80))
    MENS2 = Column(String(80))
    MENS3 = Column(String(80))
    MENS4 = Column(String(80))
    MENS5 = Column(String(80))
    MENS6 = Column(String(80))
    MENS7 = Column(String(80))
    MENS8 = Column(String(80))
    incest = Column(String(20), default='')
    bairro = Column(String(20))
    fone = Column(String(30), default='')
    fax = Column(String(30), default='')
    motivo = Column(String(80), default='')
    aprov_check = Column(Boolean)
    demissao = Column(DateTime)
    enviacarta = Column(String(1), default='X')
    motivo2 = Column(String(80))
    ddesc = Column(DateTime)
    p_liquido = Column(Numeric(18, 2))
    confirma = Column(SmallInteger, default=0)
    bord_reprovados = Column(String(1))
    valor_serasa = Column(Numeric(18, 2))
    email = Column(String(50), default='')
    critica_FIDC = Column(Integer)
    fonecob = Column(String(30), default='')
    FATURA = Column(String(14), default='')
    vfatura = Column(Numeric(18, 2), default=0)
    NFEChave = Column(String(44), default='')
    STATUS_NF = Column(Integer, default=0)
    datasaida = Column(DateTime)
    tcobran = Column(Integer)
    rgb_criou_nossono = Column(Boolean, default=False)
    NFESERIE = Column(String(3), default='')
    RaizCnpj = Column(String(14), default='')
    RecompraParcial = Column(Numeric(18, 2), default=0)
    id_produto = Column(Integer, default=0)
    Abatimento = Column(Numeric(18, 2))
    NS_CodigoVerificacao = Column(String(32), default='')
    
    def __repr__(self):
        return f"<APRTitulos(NUMERO={self.NUMERO}, TITULO={self.TITULO}, VALOR={self.VALOR})>"


class APRCapa(Base):
    """
    ORM model for APR_capa table.
    Represents the header/cover information for APR proposals.
    """
    __tablename__ = 'APR_capa'
    
    # Primary Key (composite)
    DATA = Column(DateTime, primary_key=True, nullable=False)
    NUMERO = Column(Integer, primary_key=True, nullable=False)
    
    # Regular columns
    CEDENTE = Column(String(20))
    GERENTE = Column(String(10))
    BORDERO = Column(Integer)
    TAXA = Column(Numeric(18, 2))
    TXSERV = Column(Numeric(18, 2))
    RECOMPRA = Column(Numeric(18, 2))
    QTD_PROPOSTOS = Column(Integer)
    VLR_PROPOSTOS = Column(Numeric(18, 2))
    QTD_APROVADOS = Column(Integer)
    VLR_APROVADOS = Column(Numeric(18, 2))
    QTD_REP_GER = Column(Integer)
    VLR_REP_GER = Column(Numeric(18, 2))
    QTD_REP_DIR = Column(Integer)
    VLR_REP_DIR = Column(Numeric(18, 2))
    QTD_REP_TOT = Column(Integer)
    VLR_REP_TOT = Column(Numeric(18, 2))
    QTD_APR_GER = Column(Integer)
    VLR_APR_GER = Column(Numeric(18, 2))
    QTD_APR_DIR = Column(Integer)
    VLR_APR_DIR = Column(Numeric(18, 2))
    QTD_NA = Column(Integer)
    VLR_NA = Column(Numeric(18, 2))
    SEQUENCIAL = Column(Integer, nullable=False)
    empresa = Column(String(10))
    tipo_operacao = Column(Integer)
    bordero2 = Column(Integer)
    origem = Column(SmallInteger)
    fechado = Column(Boolean)
    p_empresa = Column(String(10))
    p_dmais = Column(SmallInteger)
    p_criterio = Column(SmallInteger)
    p_data_cadastro = Column(DateTime)
    p_vtt = Column(Numeric(18, 2))
    p_df = Column(Numeric(18, 2))
    p_servico = Column(Numeric(18, 2))
    p_txiss = Column(Numeric(18, 2))
    p_iss = Column(Numeric(18, 2))
    p_txiof = Column(Numeric(18, 5))
    p_iof = Column(Numeric(18, 2))
    p_txdoc = Column(Numeric(18, 2))
    p_liqdoc = Column(Numeric(18, 2))
    p_tliqdoc = Column(Numeric(18, 2))
    p_txsaque = Column(Numeric(18, 2))
    p_liqsaque = Column(Numeric(18, 2))
    p_tliqsaque = Column(Numeric(18, 2))
    p_nche = Column(Integer)
    p_vche = Column(Numeric(18, 2))
    p_tche = Column(Numeric(18, 2))
    p_ndup = Column(Integer)
    p_vdup = Column(Numeric(18, 2))
    p_tdup = Column(Numeric(18, 2))
    p_ndoc = Column(Integer)
    p_vdoc = Column(Numeric(18, 2))
    p_tdoc = Column(Numeric(18, 2))
    p_cpmf = Column(Numeric(18, 5))
    p_vcpmf = Column(Numeric(18, 2))
    p_tcpmf = Column(Numeric(18, 2))
    p_adicional = Column(Numeric(18, 2))
    p_db = Column(Numeric(18, 2))
    p_liquido = Column(Numeric(18, 2))
    p_recompra = Column(Numeric(18, 2))
    p_perc_retencao_ir = Column(Numeric(18, 2))
    p_retencao_ir = Column(Numeric(18, 2))
    p_perc_retencao2_total = Column(Numeric(18, 2))
    p_retencao2_total = Column(Numeric(18, 2))
    p_pago = Column(Numeric(18, 2))
    p_tdesconto = Column(Numeric(18, 2))
    bordero3 = Column(Integer)
    p_viof_adicional = Column(Numeric(18, 5))
    observacao = Column(String(2000))
    p_serasa = Column(Numeric(18, 2))
    txservcs = Column(Numeric(18, 2))
    p_adicional3 = Column(Numeric(18, 2))
    datahora_bord_cria = Column(DateTime)
    datahora_bord_pago = Column(DateTime)
    dataentrada = Column(DateTime)
    status_atual = Column(String(20))
    usuario = Column(String(20))
    taxa_efetiva = Column(Numeric(18, 5))
    numero_remessa_quicksoft = Column(String(20))
    p_CBNCHE = Column(Integer)
    p_CBNDUP = Column(Integer)
    p_CBNDOC = Column(Integer)
    p_CBCPMF = Column(Numeric(18, 5))
    p_CBVCHE = Column(Numeric(18, 2))
    p_CBVDUP = Column(Numeric(18, 2))
    p_CBVDOC = Column(Numeric(18, 2))
    p_CBVCPMF = Column(Numeric(18, 2))
    p_CBTCHE = Column(Numeric(18, 2))
    p_CBTDUP = Column(Numeric(18, 2))
    p_CBTDOC = Column(Numeric(18, 2))
    p_CBTCPMF = Column(Numeric(18, 2))
    p_TOTCB = Column(Numeric(18, 2))
    p_TRECEITA = Column(Numeric(18, 2))
    p_TDESPESA = Column(Numeric(18, 2))
    p_LUCRO = Column(Numeric(18, 2))
    p_MARGEM = Column(Numeric(18, 2))
    p_MARGEM30 = Column(Numeric(18, 2))
    p_NPIS = Column(Numeric(18, 2))
    p_VPIS = Column(Numeric(18, 2))
    p_TPIS = Column(Numeric(18, 2))
    p_NFIN = Column(Numeric(18, 2))
    p_VFIN = Column(Numeric(18, 2))
    p_TFIN = Column(Numeric(18, 2))
    p_NISS = Column(Numeric(18, 2))
    p_VISS = Column(Numeric(18, 2))
    p_TISS2 = Column(Numeric(18, 2))
    p_NIOF = Column(Numeric(18, 5))
    p_VIOF = Column(Numeric(18, 2))
    p_TIOF = Column(Numeric(18, 2))
    p_TOTIMP = Column(Numeric(18, 2))
    p_NIRPJ = Column(Numeric(18, 2))
    p_VIRPJ = Column(Numeric(18, 2))
    p_TIRPJ = Column(Numeric(18, 2))
    p_NCSOCIAL = Column(Numeric(18, 2))
    p_VCSOCIAL = Column(Numeric(18, 2))
    p_TCSOCIAL = Column(Numeric(18, 2))
    p_TIPO_CUSTO = Column(Numeric(18, 2))
    p_CDBANO = Column(Numeric(18, 2))
    p_CDBMES = Column(Numeric(18, 2))
    p_DC = Column(SmallInteger)
    p_DU = Column(SmallInteger)
    p_TIPO_CDI = Column(Numeric(18, 2))
    p_TOVER = Column(Numeric(18, 2))
    p_TOTCC = Column(Numeric(18, 2))
    p_CCDMAIS = Column(SmallInteger)
    p_JB = Column(Numeric(18, 2))
    p_VJB = Column(Numeric(18, 2))
    p_IOF_CUSTOS = Column(Numeric(18, 5))
    p_VIOF_CUSTOS = Column(Numeric(18, 2))
    p_VTAC = Column(Numeric(18, 2))
    destino_data = Column(DateTime)
    destino_numero = Column(Integer)
    destino = Column(Boolean)
    STATUSAUTORIZACAO = Column(Integer)
    id_filial = Column(Integer)

    def __repr__(self):
        return f"<APRCapa(NUMERO={self.NUMERO}, CEDENTE={self.CEDENTE}, GERENTE={self.GERENTE})>"


class Cedente(Base):
    """
    ORM model for cedente table.
    Represents client/cedente information in the system.
    """
    __tablename__ = 'cedente'

    # Primary Key
    apelido = Column(String(20), primary_key=True, nullable=False)

    # Required columns
    nome = Column(String(52), nullable=False)
    cnpj = Column(String(14), nullable=False)
    simples = Column(Boolean, nullable=False)
    ativo = Column(Boolean, nullable=False)
    internet = Column(Boolean, nullable=False)
    reapresenta = Column(Boolean, nullable=False)
    cedentefidc = Column(Integer, nullable=False, default=0)
    tipocedente = Column(Integer, nullable=False, default=0)
    ID = Column(Integer, nullable=False)

    # Optional columns
    endereco = Column(String(70))
    bairro = Column(String(20))
    cidade = Column(String(20))
    uf = Column(CHAR(2))
    cep = Column(CHAR(8))
    incest = Column(String(20))
    fone = Column(String(30))
    fax = Column(String(15))
    gerente = Column(String(10))
    contato = Column(String(20))
    ramo = Column(String(20))
    grupo = Column(String(20))
    ingresso = Column(DateTime)
    ncontrato = Column(CHAR(10))
    dcontrato = Column(DateTime)
    oficio = Column(CHAR(5))
    dcartorio = Column(DateTime)
    metodo = Column(CHAR(2))
    forma = Column(CHAR(10))
    dtconst = Column(DateTime)
    regjuntacom = Column(String(15))
    nire = Column(String(15))
    atividade = Column(String(4000))
    auxiliar = Column(CHAR(10))
    gantigo = Column(CHAR(10))
    financeiro = Column(CHAR(10))
    cobranca1 = Column(CHAR(10))
    cobranca2 = Column(CHAR(10))
    cobrador = Column(CHAR(10))
    obs1 = Column(Text)
    obs2 = Column(Text)
    dlimite = Column(DateTime)
    l_valor = Column(Numeric(18, 2))
    l_acum = Column(Numeric(18, 2))
    l_titulos = Column(Integer)
    l_sac = Column(Numeric(18, 2))
    l_nconf = Column(Numeric(18, 2))
    tdesc = Column(Numeric(18, 2))
    dmais = Column(SmallInteger)
    class_plc = Column(String(5))
    class_ris = Column(String(5))
    finferior1 = Column(Numeric(18, 2))
    finferior2 = Column(Numeric(18, 2))
    fsuperior1 = Column(Numeric(18, 2))
    fsuperior2 = Column(Numeric(18, 2))
    prazo = Column(SmallInteger)
    l_acumch = Column(Numeric(18, 2))
    l_acumdp = Column(Numeric(18, 2))
    l_sacch = Column(Numeric(18, 2))
    l_sacdp = Column(Numeric(18, 2))
    instrcob1 = Column(CHAR(2))
    instrcob2 = Column(CHAR(2))
    diasprotesto = Column(CHAR(2))
    TxAcerto = Column(Numeric(18, 2))
    PCONFIR = Column(Numeric(18, 2))
    conta1 = Column(String(18))
    conta2 = Column(String(18))
    conta3 = Column(String(18))
    conta4 = Column(String(18))
    conta5 = Column(String(18))
    conta6 = Column(String(18))
    conta7 = Column(String(18))
    conta_cc = Column(String(18))
    hist_cc = Column(Integer)
    CNPJMIN = Column(Numeric(18, 2), default=0)
    VENCCNPJ = Column(DateTime)
    VENCLIMITE = Column(DateTime)
    EMAILCED = Column(String(50))
    CONC_CNPJ = Column(Numeric(18, 2))
    QDR1_2P = Column(String(18))
    QDR1_3P = Column(String(18))
    QDR1_4P = Column(String(18))
    QDR1_6P = Column(String(18))
    QDR1_7P = Column(String(18))
    CONTA_REEMB = Column(String(18))
    expsci = Column(Boolean)
    expser = Column(Boolean)
    ckobs = Column(Boolean)
    txserv = Column(Numeric(18, 2))
    db1 = Column(Numeric(18, 2))
    db2 = Column(Numeric(18, 2))
    db3 = Column(Numeric(18, 2))
    db4 = Column(Numeric(18, 2))
    TAR1 = Column(Numeric(18, 2))
    TAR2 = Column(Numeric(18, 2))
    TAR3 = Column(Numeric(18, 2))
    TAR4 = Column(Numeric(18, 2))
    TAR5 = Column(Numeric(18, 2))
    TAR6 = Column(Numeric(18, 2))
    TAR7 = Column(Numeric(18, 2))
    TAR8 = Column(Numeric(18, 2))
    TAR9 = Column(Numeric(18, 2))
    TAR10 = Column(Numeric(18, 2))
    TAR11 = Column(Numeric(18, 2))
    TAR12 = Column(Numeric(18, 2))
    TAR13 = Column(Numeric(18, 2))
    TAR14 = Column(Numeric(18, 2))
    em0 = Column(Boolean)
    em1 = Column(Boolean)
    em2 = Column(Boolean)
    em3 = Column(Boolean)
    em4 = Column(Boolean)
    em5 = Column(Boolean)
    tipo_email = Column(Integer)
    em6 = Column(Boolean)
    web1 = Column(Boolean)
    web2 = Column(Boolean)
    web3 = Column(Boolean)
    web4 = Column(Boolean)
    web5 = Column(Boolean)
    web6 = Column(Boolean)
    web7 = Column(Boolean)
    web8 = Column(Boolean)
    web9 = Column(Boolean)
    web10 = Column(Boolean)
    web11 = Column(Boolean)
    web12 = Column(Boolean)
    web13 = Column(Boolean)
    web14 = Column(Boolean)
    web15 = Column(Boolean)
    celular = Column(String(15))
    transf_auto = Column(Boolean)
    complemento = Column(Text)
    corrigepos = Column(Boolean)
    vencimento = Column(DateTime)
    tipo_tar_prorrog = Column(Integer)
    email1 = Column(String(50))
    email2 = Column(String(50))
    email3 = Column(String(50))
    email4 = Column(String(50))
    email5 = Column(String(50))
    baixa = Column(Boolean)
    dcontratomp = Column(DateTime)
    ncontratomp = Column(String(10))
    txacertopos = Column(Numeric(18, 2))
    txmora = Column(Numeric(18, 2))
    mens1 = Column(String(40))
    mens2 = Column(String(40))
    mens3 = Column(String(40))
    mens4 = Column(String(40))
    mens5 = Column(String(40))
    mens6 = Column(String(40))
    mens7 = Column(String(40))
    mens8 = Column(String(40))
    ADICIONAL2 = Column(Numeric(18, 2))
    txmorarec = Column(Numeric(18, 2))
    tac = Column(Numeric(18, 2))
    IMAGEM = Column(String(200))
    ckliquidez = Column(Boolean)
    limitech = Column(Numeric(18, 2))
    codcont = Column(String(5))
    em7 = Column(Boolean)
    em8 = Column(Boolean)
    multa = Column(Numeric(18, 2))
    adicional_lavoro = Column(String(5))
    redep_chq = Column(Boolean)
    web16 = Column(Boolean)
    web17 = Column(Boolean)
    web18 = Column(Boolean)
    taxamin = Column(Numeric(18, 2))
    prazomin = Column(Integer)
    prazomax = Column(Integer)
    atcli = Column(String(5))
    atadt = Column(String(5))
    pasgt = Column(String(5))
    web19 = Column(Boolean)
    web20 = Column(Boolean)
    web21 = Column(Boolean)
    web22 = Column(Boolean)
    web23 = Column(Boolean)
    web24 = Column(Boolean)
    web25 = Column(Boolean)
    web26 = Column(Boolean)
    web27 = Column(Boolean)
    web28 = Column(Boolean)
    web29 = Column(Boolean)
    valor_contrato = Column(Numeric(18, 2))
    limite_mp = Column(Numeric(18, 2))
    retencao_iss = Column(Boolean)
    web30 = Column(Boolean)
    cobra_dif_mora = Column(Boolean)
    cred_dif_mora = Column(Boolean)
    ncontratofidc = Column(String(10))
    tdesc_fidc = Column(Numeric(18, 2))
    txserv_fidc = Column(Numeric(18, 2))
    revisao_cadastro = Column(DateTime)
    web31 = Column(Boolean)
    dcontratotrustee = Column(DateTime)
    ncontratotrustee = Column(String(10))
    CAP_DB_BOLETO = Column(Numeric(18, 2))
    CAP_DB_CHEQUE = Column(Numeric(18, 2))
    CAP_DB_CONSUMO = Column(Numeric(18, 2))
    CAP_DB_DARF = Column(Numeric(18, 2))
    CAP_DB_DARFS = Column(Numeric(18, 2))
    CAP_DB_DEPOSITO = Column(Numeric(18, 2))
    perc_margem = Column(Numeric(18, 2))
    em9 = Column(Boolean)
    obrig_terc = Column(String(18))
    web32 = Column(Boolean)
    dcontratofidc = Column(DateTime)
    ingresso_p = Column(DateTime)
    inscricao_m = Column(String(20))
    em10 = Column(Boolean)
    rating_inicial_equifax = Column(Integer)
    rating_inicial_carteira = Column(Integer)
    rating_inicial_total = Column(Integer)
    rating_atual_equifax = Column(Integer)
    rating_atual_carteira = Column(Integer)
    rating_atual_total = Column(Integer)
    codmunicipio = Column(String(10))
    cap_classif_despesa = Column(Integer)
    tarifavencido = Column(Numeric(18, 2))
    CAP_DB_GPS = Column(Numeric(18, 2))
    CAP_DB_FGTS = Column(Numeric(18, 2))
    boleto_banco = Column(String(15))
    boleto_tcobran = Column(Integer)
    web15b = Column(Boolean)
    banco_instrucao = Column(String(15))
    id_cnae = Column(Integer)
    boleto_tcobran_s = Column(Integer)
    emailNFSE = Column(String(50))
    txprorrogacao = Column(Numeric(18, 2))
    ckcobraser = Column(Boolean)
    web33 = Column(Boolean)
    web34 = Column(Boolean)
    tdescfidc = Column(Numeric(18, 2))
    minimo_cartorio = Column(Numeric(18, 2))
    tdesccs = Column(Numeric(18, 2))
    txservCS = Column(Numeric(18, 2))
    comissao = Column(Numeric(18, 2))
    adicional3 = Column(Numeric(18, 2))
    multa_redeposito = Column(Numeric(18, 2))
    cobra_equifax = Column(Boolean)
    lcnpjNaoConf = Column(Numeric(18, 2))
    riscomax_caf_valor = Column(Numeric(18, 2))
    riscomax_caf_qtd = Column(Integer)
    web35 = Column(Boolean)
    venc_contratomp = Column(DateTime)
    limminconf = Column(Numeric(18, 2))
    ckretorno_exfactoring = Column(Boolean)
    ckretorno_recompra = Column(Boolean)
    em11 = Column(Boolean)
    em12 = Column(Boolean)
    rs01 = Column(Boolean)
    rs02 = Column(Boolean)
    rs03 = Column(Boolean)
    rs04 = Column(Boolean)
    rs05 = Column(Boolean)
    rs06 = Column(Boolean)
    rsemail = Column(String(200))
    Msg_webfact_texto = Column(Text)
    Msg_webfact_prioridade = Column(Integer)
    txservCap = Column(Numeric(18, 2))
    web36 = Column(Boolean)
    tarifa_manut_conta = Column(Numeric(18, 2))
    tarifa_revisao_credito = Column(Numeric(18, 2))
    tarifa_atualiza_limite = Column(Numeric(18, 2))
    tarifa_adm_dados = Column(Numeric(18, 2))
    tarifa_revisao_seguro = Column(Numeric(18, 2))
    tarifa_serasa = Column(Numeric(18, 2))
    dia_tarifa_serasa = Column(Integer)
    ckcriabordnossono = Column(Boolean)
    ckrecebe_retorno_cedente = Column(Boolean)
    l_raiz_sac = Column(Numeric(18, 2))
    SER_CUS_ACHEIRECH = Column(Numeric(18, 2))
    SER_CUS_CONCENTRE = Column(Numeric(18, 2))
    SER_CUS_CONCENTRE1 = Column(Numeric(18, 2))
    SER_CUS_CONCENTRE2 = Column(Numeric(18, 2))
    SER_CUS_CREDIT = Column(Numeric(18, 2))
    SER_CUS_RELATO = Column(Numeric(18, 2))
    SER_CUS_RELATO1 = Column(Numeric(18, 2))
    SER_CUS_RELATO2 = Column(Numeric(18, 2))
    SER_CUS_RELATO3 = Column(Numeric(18, 2))
    SER_CUS_RELATO4 = Column(Numeric(18, 2))
    BOLETOWEBFACTTIPOOPERACAO = Column(Integer)
    CREDITALL_TOKEN = Column(String(50))
    DigitaDanfeTitulo = Column(Boolean)
    CREDITALL_ULTIMO_CODIGO_CONTROLE = Column(String(20))
    CREDITALL_LOGIN = Column(String(40))
    DUPLICATA_10_DIGITOS = Column(Boolean)
    grandesoperacoes = Column(Boolean)
    ck_envia_email_vencidos = Column(Boolean)
    usuario_remetente_email_vencidos = Column(String(20))
    ckFIDC_Coobrigacao = Column(Boolean)
    dataVencContratoFidc = Column(DateTime)
    dataVencContratoTrustee = Column(DateTime)
    PEFIN_TARIFA_INCLUSAO = Column(Numeric(18, 2))
    PEFIN_TARIFA_EXCLUSAO = Column(Numeric(18, 2))
    PEFIN_MIN_DIAS = Column(Integer)
    id_template_cartaboleto = Column(Integer)
    web37 = Column(Boolean)
    WEB38 = Column(Boolean)
    INIBEcarta = Column(Boolean)
    prazomin_ch = Column(Integer)
    prazomax_ch = Column(Integer)
    SER_CUS_RELATOMAIS = Column(Numeric(18, 2))
    convenioremessaimportada = Column(String(20))
    WEB22b = Column(Boolean)
    XML_CLASSIFICACAO_RISCO = Column(Integer)
    XML_TIPO_DE_SOCIEDADE = Column(String(30))
    XML_RAMO_DE_ATIVIDADE = Column(String(20))
    XML_PORTE = Column(Integer)
    importa_desconto_multiplo = Column(Boolean)
    importa_desconto_diario = Column(Boolean)
    CKDmaisRedeposito = Column(Boolean)
    DmaisRedeposito = Column(Integer)
    WEB39 = Column(Boolean)
    CRM_STATUS = Column(Integer)
    web40 = Column(Boolean)
    numero_cc = Column(String(10), default='')
    ConvenioLydians = Column(String(20), default='')
    WEB41 = Column(Boolean, default=False)
    WEB42 = Column(Boolean, default=False)
    ECM_ID = Column(String(5), default='')
    HEADER_BRADESCO = Column(String(20), default='                    ')
    HEADER_BRADESCO_CSIMPLES = Column(String(20), default='                    ')
    HEADER_ITAU = Column(String(20), default='            ')
    HEADER_ITAU_CSIMPLES = Column(String(20), default='            ')
    ProdutoNaProposta = Column(Boolean)
    StatusChecagemNaoConfirmadoCNPJ = Column(Integer)
    EmpresaArquivoPagamento = Column(Boolean)
    TipoOperacaoArquivoPagamento = Column(Boolean)
    ConsultarNotificacao = Column(Boolean, default=False)
    LimparNotificacao = Column(Boolean, default=False)
    CadastraNovoFavorecidoLiberacao = Column(Boolean, default=False)
    VizualizaExtratoBancarioEscrowTerceiros = Column(Boolean)
    ExibirRiscoLimiteGrupo = Column(Boolean, default=False)
    ArquivoPagamentoGrafeno = Column(Boolean, default=False)
    HabilitarMRSacado = Column(Boolean, default=False)
    VisivelPefin = Column(Boolean, default=True)
    mensgrafeno = Column(String(150))
    ckdiasuteisdp = Column(Boolean, default=False)
    ckdiasuteisch = Column(Boolean, default=False)
    RetornoCampoChaveOrigem = Column(Boolean, default=False)
    HEADER_BMP = Column(String(20), default='            ')
    HEADER_BMP_CSIMPLES = Column(String(20), default='            ')
    HEADER_SANTANDER240 = Column(String(50), default='')
    HEADER_SANTANDER240_CSIMPLES = Column(String(50), default='')
    XML_QTD_ASSINATURA_TERMO = Column(Integer, default=1)
    XML_QTD_ASSINATURA_DUPLICATA = Column(Integer, default=1)
    CNPJ_EMPRESA_BRADESCO = Column(String(14), default='')
    NaoCobrarMultaCartorioCNAB = Column(Boolean)
    HEADER_REAG = Column(String(20), default='            ')
    HEADER_REAG_CSIMPLES = Column(String(20), default='            ')
    nome_fantasia = Column(String(52))
    cobrancaarqpagamento = Column(Boolean, default=False)
    ExigeProdutocriacaoBordero = Column(Boolean, default=False)
    AdicionalDBPorFaixa = Column(Boolean, default=False)
    web43 = Column(Boolean, default=True)

    def __repr__(self):
        return f"<Cedente(apelido={self.apelido}, nome={self.nome}, cnpj={self.cnpj})>"


class Produto(Base):
    """
    ORM model for Produto table.
    Represents product types in the system.
    """
    __tablename__ = 'Produto'

    Id = Column(Integer, primary_key=True)
    Descritivo = Column(String(100))

    def __repr__(self):
        return f"<Produto(Id={self.Id}, Descritivo={self.Descritivo})>"


class ProdutoAtributo(Base):
    """
    ORM model for ProdutoAtributo table.
    Represents product attributes.
    """
    __tablename__ = 'ProdutoAtributo'

    Id = Column(Integer, primary_key=True)
    IdProduto = Column(Integer, ForeignKey('Produto.Id'))

    def __repr__(self):
        return f"<ProdutoAtributo(Id={self.Id}, IdProduto={self.IdProduto})>"


class ProdutoCedente(Base):
    """
    ORM model for ProdutoCedente table.
    Links products to cedentes.
    """
    __tablename__ = 'ProdutoCedente'

    Id = Column(Integer, primary_key=True)
    IdProdutoAtributo = Column(Integer, ForeignKey('ProdutoAtributo.Id'))

    def __repr__(self):
        return f"<ProdutoCedente(Id={self.Id}, IdProdutoAtributo={self.IdProdutoAtributo})>"


class CadastroStatusFluxo(Base):
    """
    ORM model for CADASTRO_STATUS_FLUXO table.
    Represents workflow status definitions in the system.
    """
    __tablename__ = 'CADASTRO_STATUS_FLUXO'

    # Primary Key
    NOME_STATUS = Column(String(20), primary_key=True, nullable=False)

    # Regular columns
    ID = Column(Integer, nullable=False)
    TROCA_AUTOMATICA = Column(Boolean, nullable=False, default=False)
    SEMPRE_APARECE = Column(Boolean, nullable=False, default=False)
    COR = Column(String(30), nullable=False, default='')
    ENVIA_WHATSAPP = Column(Boolean, nullable=True, default=False)
    MENSAGEM_WHATSAPP = Column(String(2000), nullable=True)
    IDMENSAGEM_WHATSAPP = Column(String(100), nullable=True)

    def __repr__(self):
        return f"<CadastroStatusFluxo(NOME_STATUS={self.NOME_STATUS}, ID={self.ID}, COR={self.COR})>"

